# Generated by Django 4.1.2 on 2022-12-06 07:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity_type', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ClassKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('lat', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('lon', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('postal_code', models.CharField(max_length=32)),
                ('phone_number', models.CharField(max_length=15)),
                ('amenities', models.ManyToManyField(blank=True, to='studios.amenity')),
            ],
        ),
        migrations.CreateModel(
            name='StudioClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('class_name', models.CharField(max_length=200)),
                ('coach', models.CharField(max_length=200)),
                ('capacity', models.IntegerField()),
                ('day', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('cancelled', models.BooleanField(default=False)),
                ('date_cancelled', models.DateTimeField(blank=True, null=True)),
                ('changed', models.BooleanField(default=False)),
                ('keywords', models.ManyToManyField(blank=True, to='studios.classkeyword')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studios.studio')),
            ],
        ),
        migrations.CreateModel(
            name='StudioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studio_image', models.ImageField(upload_to='studio_images/')),
            ],
        ),
        migrations.CreateModel(
            name='UserClassInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=200)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[(0, 'Attended'), (1, 'Dropped'), (2, 'Cancelled')], default=0, max_length=200)),
                ('studio_name', models.CharField(max_length=200)),
                ('coach', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_recurring', models.BooleanField(default=True)),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studios.studio')),
                ('studio_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studios.studioclass')),
            ],
        ),
        migrations.CreateModel(
            name='UserClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_enrolled', models.DateTimeField(auto_now_add=True)),
                ('dropped', models.BooleanField(default=False)),
                ('date_dropped', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('studio_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studios.studioclass')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimeChangedClassInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_start_time', models.TimeField()),
                ('new_end_time', models.TimeField()),
                ('date', models.DateField()),
                ('studio_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studios.studioclass')),
            ],
        ),
        migrations.CreateModel(
            name='StudioClassInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('class_name', models.CharField(max_length=200)),
                ('coach', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('studio_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studios.studioclass')),
            ],
        ),
        migrations.AddField(
            model_name='studio',
            name='images',
            field=models.ManyToManyField(blank=True, to='studios.studioimage'),
        ),
        migrations.CreateModel(
            name='EnrolledClassInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_date', models.DateField()),
                ('studio_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studios.studioclass')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DroppedClassInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_dropped', models.DateField()),
                ('studio_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studios.studioclass')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CancelledClassInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_cancelled', models.DateField()),
                ('studio_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studios.studioclass')),
            ],
        ),
    ]
